[package]
name = "snake"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["dynamic_linking","wav"] }
bevy_asset_loader = { version = "0.24.0-rc.1" }
avian2d = "0.4"
rand = "0.9.2"


# Enable a small amount of optimization in the dev profile.

